stages:
  - test
  - deploy

build:
  image: node:18-alpine
  stage: test
  script:
    - npm ci
    - npm test
    - npm run build

Docker Run:
  image: sleavely/node-awscli:18.x
  stage: deploy
  script:
    - npm ci
    - npm run prod
  only:
    - main
    - dev
