export const ROUTES = {
  HOME_PACIENTE: () => '/home/paciente',
  HOME_MEDICO: () => '/home/medico',
  CADASTRO_PACIENTE: () => '/cadastro/paciente',
  CADASTRO_MEDICO: () => '/cadastro/medico',
  IDENTIFICACAO: () => '/identificacao',
  EXAMES_PENDENTES_VAZIO: () => '/perfil/exames-pendentes-vazio',
  EXAMES_REALIZADOS_VAZIO: () => '/perfil/exames-realizados-vazio',
  LOGIN: () => '*',
  PERFIL_PACIENTE: () => '/perfil/paciente',
  PERFIL_MEDICO: () => '/perfil/medico',
  MENU_MEDICAMENTOS: () => '/menu/medicamentos',
  LISTA_MEDICAMENTOS: () => '/lista/medicamentos',
  LISTA_EXAMES: () => '/lista/exames',
};
